apiVersion: v1
kind: Service
metadata:
  name: citus-coordinator
spec:
  type: NodePort
  selector:
    app: citus-coordinator
  ports:
    - port: 5432
      targetPort: 5432
      nodePort: 30432
      name: postgres
